# Автор MishaNeYT, плагин сделал для общего использования.
# Запрещено выдавать плагин за себя.

Settings:
  # true - после использования предмета игрок получит урон от падения с большого
  # расстояния. Рекомендую отключить (Default: false).
  FallDamage: false
  # Если возникли проблемы с сохранением новых предметов, используйте эту функцию.
  # Рекомендую включить (Default: true).
  AdvanceReload: true

  # Сообщения, которые будут отображаться после использования предмета.
  # Title - сообщение на экран (Можно редактировать в конфигурации messages.yml)
  # Chat - сообщение в чат (Можно редактировать в конфигурации messages.yml)
  Title: false
  Chat: true

# Настройка задержки для повторного использования предмета. Рекомендую отключить
# сервер, а потом менять эту функцию.
Cooldown:
  Enable: true
  Wait: 15
  # Сообщение настраивается в конфигурации messages.yml