# Автор MishaNeYT, плагин сделал для общего использования
# Запрещено выдавать плагин за себя.

# GitHub исходный код - SOON

Settings:
  # Не игнорировать урон от падения.
  FallDamage: false

  # Включить или отключить сообщения, которые будут отображаться после использования предмета.
  Title: false
  Chat: true

# Настройка задержки. Может возникать баг, поэтому рекомендую перезагрузить сервер.
Cooldown:
  Enable: true
  Wait: 15
  # Сообщение настраивается в messages.yml